name: ci

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build:
    name: Build Docker image
    strategy:
      matrix:
         build-image: ['zephyr-sdk-ada-base', 'zephyr-sdk-ada-build-base', 'zephyr-sdk-ada-arm', 'zephyr-sdk-ada-riscv64']
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: zephyrada/${{ matrix.build-image }} # list of Docker images to use as base name for tags
          tag-sha: false # add git short SHA as Docker tag
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.build-image }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.build-image }}-buildx-
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Move patch folder due to broken build-push-action context
        if: matrix.build-image == 'zephyr-sdk-ada-build-base'
        run: mv zephyr-sdk-ada-build-base/patches patches
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ matrix.build-image }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
